version: '3'
services:
  front:
    build:
      context: front
      args:
        - NODE_ENV=development
    ports:
      - 8080

  portal:
    image: steveltn/https-portal:latest
    ports:
      - '443:443'
    environment:
      STAGE: local
      DOMAINS: 'localhost -> http://front:8080/'
    links:
      - front
